apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  annotations:
    notifications.argoproj.io/subscribe.on-deployed.slack: test_slack_plugin
  name: istio-rollouts
spec:
  project: default  # Replace with your desired ArgoCD project
  source:
    repoURL: https://github.com/pasha-codefresh/argo-cd-suite
    targetRevision: HEAD  # Replace with the target revision (commit, tag, or branch)
    path: ./manifests/applications/istio-rollouts/resources
  destination:
    server: https://kubernetes.default.svc  # Replace with your Kubernetes cluster API URL
    namespace: codefresh
  syncPolicy:
    syncOptions:
      - CreateNamespace=true
