apiVersion: v1
data:
  policy.csv: |
    p, pasha, applications, create,    cf/cf-argocd/*, allow # Working to create app
    p, role:user, applications, get, cf/cf-argocd/*, allow
    p, pasha, applications, action/*, cf/cf-argocd/*,  allow # Working if I execute an action on a resource
    p, pasha, applications, update, cf/cf-argocd/*, allow # Working if I update a resource
    p, pasha, logs, get, cf/cf-argocd/*,  allow # Working if I get logs
    p, role:user, exec, create, cf/cf-argocd/*, allow
    g, pasha, role:user
kind: ConfigMap
metadata:
  annotations:
    kubectl.kubernetes.io/last-applied-configuration: |
      {"apiVersion":"v1","kind":"ConfigMap","metadata":{"annotations":{},"labels":{"app.kubernetes.io/name":"argocd-rbac-cm","app.kubernetes.io/part-of":"argocd"},"name":"argocd-rbac-cm","namespace":"argocd"}}
  creationTimestamp: "2024-08-27T09:32:22Z"
  labels:
    app.kubernetes.io/name: argocd-rbac-cm
    app.kubernetes.io/part-of: argocd
  name: argocd-rbac-cm
  namespace: argocd
  resourceVersion: "83175"
  uid: 461a2f51-f0ef-4313-baad-54b2981b573b