apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: incorrect-secret-connector
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    repoURL: https://github.com/pasha-codefresh/argo-cd-suite
    path: ./manifests/applications/broken-secret
    targetRevision: HEAD
  destination:
    server: https://kubernetes.default.svc
    namespace: codefresh
  syncPolicy:
    syncOptions:
      - CreateNamespace=true
      - ServerSideApply=true
    automated:
      prune: true
      selfHeal: true
